name: Primer parcial: despliegue automatico

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Traer el proyecto
        uses: actions/checkout@v4

      - name: Preparar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar Surge
        run: npm install --global surge

      - name: Enviar pagina a la nube
        run: surge ./ ${{ secrets.SURGE_DOMAIN }}
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}